#
# Copyright (c) 2019-2023 cnbbx <https://cnbbx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
name: build-openWrt
run-name: æˆ‘çš„OpenWrtäº‘ç¼–è¯‘ï¼š${{ inputs.TITLE_SHOW }}
env:
  REPO_URL: https://github.com/cnbbx/Openwrt-src.git
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  BUILD_USER: ${{ github.actor }}
  TZ: Asia/Shanghai

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      UPLOAD_BIN_DIR:
        description: ' ä¿å­˜ç¼–è¯‘åçš„å…¨éƒ¨æ–‡ä»¶'
        type: boolean
        default: true
      UPLOAD_WETRANSFER:
        description: 'å‘å¸ƒå›ºä»¶åˆ°Wetransfer'
        type: boolean
        default: true
      UPLOAD_RELEASE:
        description: 'å‘å¸ƒå›ºä»¶åˆ°Releases'
        type: boolean
        default: true
      TITLE_SHOW:
        type: string
        description: ä»»åŠ¡æµç¨‹æ ‡é¢˜
  schedule:
    - cron: '5 22 * * 0'

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/cnbbx/openwrt-tools:min
    strategy:
      matrix:
        include:
          - FIRMWARE_NAME: youku_yk-l2
          - FIRMWARE_NAME: d-team_newifi-d2
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: æ£€æŸ¥ç©ºé—´ä½¿ç”¨æƒ…å†µ
      working-directory: /workdir
      run: |
        echo "è­¦å‘Šâš "
        echo -e "-------------- ------------CPUä¿¡æ¯------------------------------------------\n"
        echo "CPUç‰©ç†æ•°é‡:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPUæ ¸å¿ƒåŠç‰ˆæœ¬ä¿¡æ¯ï¼š$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "-----------------------------ç¡¬ç›˜ä¿¡æ¯---------------------------------------------"
        echo -e  "ç¡¬ç›˜æ•°é‡ï¼š$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
        echo "ç¡¬ç›˜è¯¦æƒ…ï¼š"
        df -Th

    - name: å…‹éš†è½¯è·¯ç”±æºä»£ç 
      run: |
        git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt
        mkdir -p /workdir/openwrt/staging_dir /workdir/openwrt/build_dir
        ln -sf /workdir/staging_dir/host /workdir/openwrt/staging_dir/host
        ln -sf /workdir/build_dir/host /workdir/openwrt/build_dir/host 
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: ä¸‹è½½è‡ªå®šä¹‰é¡¹ç›®çš„æ¸…å•
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        cd openwrt && ./scripts/feeds update -a

    - name: å®‰è£…è‡ªå®šä¹‰é¡¹ç›®çš„æ¸…å•
      run: cd openwrt && ./scripts/feeds install -a

    - name: åŠ è½½è‡ªå®šä¹‰å›ºä»¶é…ç½®
      if: (!cancelled())
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e ${{ matrix.FIRMWARE_NAME }}.config ] && mv ${{ matrix.FIRMWARE_NAME }}.config openwrt/.config
        [ -e ${{ matrix.FIRMWARE_NAME }}.sh ] && mv ${{ matrix.FIRMWARE_NAME }}.sh openwrt/diy.sh
        cd openwrt/ && chmod +x diy.sh && ./diy.sh

    - name: ä¸‹è½½è‡ªå®šä¹‰å›ºä»¶æ’ä»¶
      id: package
      if: (!cancelled())
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ç¼–è¯‘å›ºä»¶
      id: compile
      if: (!cancelled())
      run: |
        cd openwrt && mkdir -p firmware
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s || true
        cd bin/targets/*/*
        mv *.buildinfo *.bin *.manifest $GITHUB_WORKSPACE/openwrt/firmware

    - name: ä¿å­˜ç¼–è¯‘åçš„å›ºä»¶æ–‡ä»¶
      uses: actions/upload-artifact@main
      if: inputs.UPLOAD_BIN_DIR == true || inputs.UPLOAD_BIN_DIR == ''
      with:
        name: OpenWrt_Firmware
        path: openwrt/firmware

    - name: ä¿å­˜ç¼–è¯‘åçš„æ’ä»¶æ–‡ä»¶
      uses: actions/upload-artifact@main
      if: inputs.UPLOAD_BIN_DIR == true || inputs.UPLOAD_BIN_DIR == ''
      with:
        name: OpenWrt_Packages
        path: openwrt/bin

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: è°ƒå–ç¼–è¯‘åçš„å›ºä»¶æ–‡ä»¶
      uses: actions/download-artifact@main
      with:
        name: OpenWrt_Firmware
        path: openwrt/firmware
        
    - name: è°ƒå–ç¼–è¯‘åçš„æ’ä»¶æ–‡ä»¶
      uses: actions/download-artifact@main
      with:
        name: OpenWrt_Packages
        path: openwrt/bin

    - name: ä¼˜åŒ–éœ€è¦å‘å¸ƒçš„å›ºä»¶
      id: organize
      if: (!cancelled())
      working-directory: /workdir
      run: cd openwrt && tar -zcvf firmware/Packages.tar.gz bin

    - name: å‘å¸ƒå›ºä»¶åˆ°WeTransfer
      id: wetransfer
      if: (inputs.UPLOAD_WETRANSFER == true || inputs.UPLOAD_WETRANSFER == '') && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress openwrt/firmware 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "url=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT

    - name: ç”Ÿæˆ release tag
      id: tag
      if: (inputs.UPLOAD_RELEASE == true || inputs.UPLOAD_RELEASE == '') && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        cat >> release.txt <<EOF
        1ã€æœ¬å›ºä»¶ä¸ºè‡ªåŠ¨ç¼–è¯‘
        2ã€å‘è¡Œç‰ˆä¸­åªæä¾›å®Œæ•´çš„å›ºä»¶
        3ã€æºç ï¼š${{ env.REPO_URL }}
        -- Build by ${{ env.BUILD_USER }} @ with Github Action on $(date +"%Y.%m.%d-%H%M")
        ğŸš€ Auto build | è‡ªåŠ¨ç¼–è¯‘
        EOF
        [ ${{ inputs.UPLOAD_COWTRANSFER }} = true ] && echo "ğŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ ${{ inputs.UPLOAD_WETRANSFER }} = true ] && echo "ğŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt

    - name: ä¸Šä¼ å›ºä»¶åˆ°release
      uses: softprops/action-gh-release@v1
      if: (inputs.UPLOAD_RELEASE == true || inputs.UPLOAD_RELEASE == '') && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: openwrt/firmware/*

    - name: ç§»é™¤è€çš„ workflow runs
      uses: zhoujinshi/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: ç§»é™¤è€çš„ Releases
      uses: dev-drprasad/delete-older-releases@master
      if: (inputs.UPLOAD_RELEASE == true || inputs.UPLOAD_RELEASE == '') && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
